#!/bin/bash

set -e

# Check for appropriate number of arguments
if [[ $# -ne 1 ]]; then
    echo Usage: create-ppa version
    exit 1
fi

# First argument is version (remove any hyphens)
version=${1//-/}

# Only Ubuntu 15.04+ support HDF5 with F2003 API
# 15.04 = vivid
# 15.10 = wily
# 16.04 = xenial
release=wily

# Step 1 -- get OpenMC source and create an archive given the tag
if [[ ! -e openmc_${version}.orig.tar.gz ]]; then
    git clone --recursive git@github.com:mit-crpg/openmc.git
    cd openmc
    ../git-archive-all.sh --prefix openmc-${version}/ -t v${version} ../openmc_${version}.orig.tar
    cd ..
    gzip -n openmc_${version}.orig.tar
    rm -rf openmc
fi

# Step 2 -- Extract created archive and copy debian files
tar xvf openmc_${version}.orig.tar.gz
cd openmc-${version}
cp -R ../debian-files debian

# Step 3 -- Edit changelog
dch -b -v ${version}-0ubuntu1~${release}ppa1 --package openmc \
    -D ${release}
cp debian/changelog ../debian-files/

# Step 4 -- Build the Debian package
debuild -S -sa
cd ..

# Step 5 -- Upload to launchpad
echo -e "Now run \e[34mdput ppa:paulromano/staging openmc_${version}-0ubuntu1~${release}ppa1_source.changes\e[0m"
